### PR TITLE
[MP-380] Remove deprecation warning as we are now maintaining this step for better or for worse

### PR DESCRIPTION
**Pull request by elashpear**
This is a trivial change but I kicked off a resign job at https://app.bitrise.io/build/882d87b6c57cf127#?tab=log just to verify no issues arise

### CODE REVIEW

**Comment by elashpear** [comment]
lol @jasonfma I see you

**Comment by jasonfma** [comment]
Why am I still getting notifications for this stuff? :p

**Comment by jjosephpear** [comment]
Omg there is a ghost in our repos

**Review by jjosephpear — APPROVED** [review]

**Comment by elashpear** [comment]
@jasonfma hah, I think you created this repo on your personal account so you're still watching it! and it's a public fork....

**Pull request merged**
